management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
server:
  port: 8081
  servlet:
    context-path: /kitchensink
spring:
  application:
    name: kitchensink
  data:
    mongodb:
      uri: mongodb://localhost:27017/testdb
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .xhtml



#http://localhost:8081/kitchensink/swagger-ui/index.html#/
